name = "DAMMmodel"
uuid = "7af7f183-cd03-4039-bf6b-67ea3eb1648d"
authors = ["Alexis Renchon et al."]
version = "0.1.3"

[deps]

[compat]
julia = "1.7"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
